
export const TOKEN_CONTRACT_ADDRESS =
"0x36ce8E77DC1Ced22C7e91AfFD79e9Bc7E5181EA5";
export const TOKEN_CONTRACT_ABI = "ABI-CRYPTO-DEV-TOKEN-CONTRACT";
export const EXCHANGE_CONTRACT_ABI = "ABI-EXCHANGE-CONTRACT";
export const EXCHANGE_CONTRACT_ADDRESS = "ADDRESS-EXCHANGE-CONTRACT";